### ISSUE TITLE
Issues with CentOS 7/8/AlmaLinux 8 and firewalld still in the script

### ISSUE THREAD

**Issue by theRolento** [Angristan/OpenVPN-install#994] opened 2022-04-08 19:10 UTC
### Make sure your check these beforehand!

- [X] Issues - https://github.com/angristan/openvpn-install/issues
- [X] README and FAQ - https://github.com/angristan/openvpn-install
- [X] Wiki - https://github.com/angristan/openvpn-install/wiki
- [X] Discussions - https://github.com/angristan/openvpn-install/discussions

### Server OS

CentOS 7 / CentOS 8 / AlmaLinux 8

### OpenVPN version

2.5.6

### Client

Windows 11

### What is the bug?

The three OS use firewalld and not iptables.
Apparently by manually executing these commands everything will work:
```
# firewall-cmd --add-service openvpn
# firewall-cmd --permanent --add-service openvpn
# firewall-cmd --add-masquerade
# firewall-cmd --permanent --add-masquerade
```

**Comment by angristan** [comment] 2023-01-21 23:59
Closing as duplicate of https://github.com/angristan/openvpn-install/issues/356

**Closed as not planned by angristan** 2023-01-21 23:59 UTC
Labels: duplicate
