### ISSUE TITLE
[Bug]: Script not generating TLS Certificate

### ISSUE THREAD

**Issue by Kye-NG** [Angristan/OpenVPN-install#1068] opened 2022-12-03 09:29 UTC
### Make sure your check these beforehand!

- [X] Issues - https://github.com/angristan/openvpn-install/issues
- [X] README and FAQ - https://github.com/angristan/openvpn-install
- [X] Wiki - https://github.com/angristan/openvpn-install/wiki
- [X] Discussions - https://github.com/angristan/openvpn-install/discussions

### Server OS

Debian 11 Bullseye

### Client

OpenVPN GUI windows 11

### What is the bug?

When running the script it and generating a client config file, the script does not generate any TLS certs. The config has an empty `<tls-crypt>` element and makes the config error. Removing the empty `<tls-crypt>` element makes the TLS handshake fail.

I've checked `/etc/openvpn/` and it doesn't have either the `tls-crypt.key` file nor the `tls-auth.key`.

Not sure how to fix it.

**Comment by andreagobetti** [comment] 2023-01-13 11:33
This is the same as #1057

**Comment by angristan** [comment] 2023-01-21 23:26
Closing as duplicate of https://github.com/angristan/openvpn-install/issues/1057

**Closed as not planned by angristan** 2023-01-21 23:26 UTC
Labels: duplicate
