### ISSUE TITLE
Script does not work when seeip.org is unreachable

### ISSUE THREAD

**Issue by gbnk0** [Angristan/OpenVPN-install#1241] opened 2024-08-07 11:20 UTC
```
./openvpn-install.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0^C
```

It does a curl to ip.seeip.org . When seeip.org is down or unreachable it dos not work. I think it will tell something like "unable to get the public ip" or anything else.

I thin the concerned lines are:

```
			if ! PUBLIC_IP=$(curl -f --retry 5 --retry-connrefused https://ip.seeip.org); then
			if ! PUBLIC_IP=$(curl -f --retry 5 --retry-connrefused -4 https://ip.seeip.org); then
```
Regards

**Comment by dolbykoray** [comment] 2024-08-09 05:07
Senin sorunu`apt install iftop` çözebilir denedin mi? Belkide sorununu yanlış anladım selamlar.

**Comment by gbnk0** [comment] 2024-08-09 07:15
The curl is trying indefinitely to hit ip.seeip.org, so in this case you can't access to the options for creating new vpn clients.
Update:

This happens only when i pass env vars in my shell before:
```
export MENU_OPTION=1 PASS=1 CLIENT=myclient AUTO_INSTALL=y ENDPOINT=servrer.publicip.org IPV6_SUPPORT=n PORT_CHOICE=2 PORT=4567 PROTOCOL_CHOICE=2
```

Regards,

**Comment by dolbykoray** [comment] 2024-08-10 02:12
Can you solve my problem? or give me some ideas?   [https://github.com/angristan/openvpn-install/issues/1242](url)

**Comment by ralphg6** [comment] 2024-08-10 18:40
I did a PR fixing it #1243.

Please @angristan, could you put your eyes on it? 

Now the script isn't working because 'ip.seeip.org' is unreachable now.

**Comment by fmuscetra** [comment] 2024-08-11 14:02
I have the same issue. My Terraform template that uses the Angristan shell script does not work anymore and it hangs when the script trying to connect to ip.seeip.org. 
It worked for months without any problem. 
The problem appears when AUTO_INSTALL = y

**Comment by ralphg6** [comment] 2024-08-11 14:38
The PR that I mentioned fix it!! Let's await some maintainer to put your eyes on it!


@fmuscetra, if you REALLY need it now, and you can't await the PR reviewing, you can use my fork temporarily! 

https://github.com/ralphg6/openvpn-install

**Comment by xiahare** [comment] 2024-10-18 21:33
I submit a PR for this problem.
It was caused by invalid url of ip.seeip.org. 
Fix: change the url of ip.seeip.org to api.seeip.org .

refer to this:
https://github.com/angristan/openvpn-install/pull/1252

**Comment by angristan** [comment] 2024-11-07 19:56
Sorry I missed this issue 🙏  #1243 and #1252 have been merged ✅ Thanks!

**Closed as completed by angristan** 2024-11-07 19:56 UTC
Labels: bug
