### ISSUE TITLE
no internet connection with google cloud (but nyr's script works)

### ISSUE THREAD

**Issue by momenthe** [angristan/openvpn-install#675] opened 2020-06-08 20:31 UTC
hi,

i've been trying to set up an openvpn server on google cloud for days but although everything seems okay, there was no connection. it was successfully connecting. i tried with centos 7/8 and ubuntu but nothing solved.

then i tried nyr's script and it worked! so i guess something's wrong with this script but i couldn't find the problem. i am not familier with linux so i couldn't understand all solutions but it might be related with this https://github.com/angristan/openvpn-install/issues/561

i'll be happy if you find and fix the issue. because i want to use this script. thank you.

**Comment by angristan** [comment] 2020-08-08 12:36
Probably duplicate of #561 if you were using CentOS 8 then :)

**Closed as completed** 2020-08-08 12:36 UTC
Labels: duplicate
